name: Build, Test, and Deploy to Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Job 1: Build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build --if-present  # Si tienes un proceso de build en tu proyecto

  # Job 2: Test
  test:
    needs: build  # Esto asegura que el test solo se ejecute si el build fue exitoso
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # Paso adicional: Otorgar permisos a Mocha si lo necesitas
      - name: Grant permission to Mocha
        run: chmod +x ./node_modules/.bin/mocha

      - name: Run tests
        run: npm test

  # Job 3: Docker Delivery
  delivery:
    needs: test  # Esto asegura que el job de delivery solo se ejecute después de que el test sea exitoso
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/infosec-chat:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/infosec-chat:latest

  # Job 4: Scan Docker Image for Vulnerabilities
  scan:
    needs: delivery  # Asegura que el escaneo se ejecute después de que la imagen Docker se haya creado
    runs-on: ubuntu-latest
    steps:
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.36.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.36.0_Linux-64bit.deb
          trivy --version  # Verifica la instalación

      - name: Scan Docker image with Trivy
        run: trivy image ${{ secrets.DOCKER_USERNAME }}/infosec-chat:latest

  # Job 5: CodeQL Analysis
  codeql:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript  # Cambia esto según el lenguaje de tu proyecto

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  # Job 6: Deploy to Azure Web App
  deploy:
    needs: [delivery, scan]  # Asegura que este job se ejecute después de que los jobs 'delivery' y 'scan' se completen
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: UNA-CHAT  # Cambia esto por el nombre de tu aplicación en Azure
          images: ${{ secrets.DOCKER_USERNAME }}/infosec-chat:latest  # Imagen Docker que se creó en el paso anterior
